/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountNumbersRouteImport } from './routes/account-numbers'
import { Route as AddCashRouteImport } from './routes/add-cash'
import { Route as CashbackRouteImport } from './routes/cashback'
import { Route as FundInstantlyRouteImport } from './routes/fund-instantly'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LinkedAccountsRouteImport } from './routes/linked-accounts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageCardsRouteImport } from './routes/manage-cards'
import { Route as MoveMoneyRouteImport } from './routes/move-money'
import { Route as MyVaroRouteImport } from './routes/my-varo'
import { Route as PayBillsRouteImport } from './routes/pay-bills'
import { Route as PersonalDetailsRouteImport } from './routes/personal-details'
import { Route as SendRouteImport } from './routes/send'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TransactionHistoryRouteImport } from './routes/transaction-history'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as VaroCardRouteImport } from './routes/varo-card'
import { Route as AccountIdRouteImport } from './routes/account.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNumbersRoute = AccountNumbersRouteImport.update({
  id: '/account-numbers',
  path: '/account-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCashRoute = AddCashRouteImport.update({
  id: '/add-cash',
  path: '/add-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbackRoute = CashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => rootRouteImport,
} as any)
const FundInstantlyRoute = FundInstantlyRouteImport.update({
  id: '/fund-instantly',
  path: '/fund-instantly',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedAccountsRoute = LinkedAccountsRouteImport.update({
  id: '/linked-accounts',
  path: '/linked-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCardsRoute = ManageCardsRouteImport.update({
  id: '/manage-cards',
  path: '/manage-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveMoneyRoute = MoveMoneyRouteImport.update({
  id: '/move-money',
  path: '/move-money',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVaroRoute = MyVaroRouteImport.update({
  id: '/my-varo',
  path: '/my-varo',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillsRoute = PayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDetailsRoute = PersonalDetailsRouteImport.update({
  id: '/personal-details',
  path: '/personal-details',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionHistoryRoute = TransactionHistoryRouteImport.update({
  id: '/transaction-history',
  path: '/transaction-history',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const VaroCardRoute = VaroCardRouteImport.update({
  id: '/varo-card',
  path: '/varo-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIdRoute = AccountIdRouteImport.update({
  id: '/account/$id',
  path: '/account/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-numbers': typeof AccountNumbersRoute
  '/add-cash': typeof AddCashRoute
  '/cashback': typeof CashbackRoute
  '/fund-instantly': typeof FundInstantlyRoute
  '/install': typeof InstallRoute
  '/linked-accounts': typeof LinkedAccountsRoute
  '/login': typeof LoginRoute
  '/manage-cards': typeof ManageCardsRoute
  '/move-money': typeof MoveMoneyRoute
  '/my-varo': typeof MyVaroRoute
  '/pay-bills': typeof PayBillsRoute
  '/personal-details': typeof PersonalDetailsRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/transaction-history': typeof TransactionHistoryRoute
  '/transfer': typeof TransferRoute
  '/varo-card': typeof VaroCardRoute
  '/account/$id': typeof AccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-numbers': typeof AccountNumbersRoute
  '/add-cash': typeof AddCashRoute
  '/cashback': typeof CashbackRoute
  '/fund-instantly': typeof FundInstantlyRoute
  '/install': typeof InstallRoute
  '/linked-accounts': typeof LinkedAccountsRoute
  '/login': typeof LoginRoute
  '/manage-cards': typeof ManageCardsRoute
  '/move-money': typeof MoveMoneyRoute
  '/my-varo': typeof MyVaroRoute
  '/pay-bills': typeof PayBillsRoute
  '/personal-details': typeof PersonalDetailsRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/transaction-history': typeof TransactionHistoryRoute
  '/transfer': typeof TransferRoute
  '/varo-card': typeof VaroCardRoute
  '/account/$id': typeof AccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-numbers': typeof AccountNumbersRoute
  '/add-cash': typeof AddCashRoute
  '/cashback': typeof CashbackRoute
  '/fund-instantly': typeof FundInstantlyRoute
  '/install': typeof InstallRoute
  '/linked-accounts': typeof LinkedAccountsRoute
  '/login': typeof LoginRoute
  '/manage-cards': typeof ManageCardsRoute
  '/move-money': typeof MoveMoneyRoute
  '/my-varo': typeof MyVaroRoute
  '/pay-bills': typeof PayBillsRoute
  '/personal-details': typeof PersonalDetailsRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/transaction-history': typeof TransactionHistoryRoute
  '/transfer': typeof TransferRoute
  '/varo-card': typeof VaroCardRoute
  '/account/$id': typeof AccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-numbers'
    | '/add-cash'
    | '/cashback'
    | '/fund-instantly'
    | '/install'
    | '/linked-accounts'
    | '/login'
    | '/manage-cards'
    | '/move-money'
    | '/my-varo'
    | '/pay-bills'
    | '/personal-details'
    | '/send'
    | '/signup'
    | '/transaction-history'
    | '/transfer'
    | '/varo-card'
    | '/account/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-numbers'
    | '/add-cash'
    | '/cashback'
    | '/fund-instantly'
    | '/install'
    | '/linked-accounts'
    | '/login'
    | '/manage-cards'
    | '/move-money'
    | '/my-varo'
    | '/pay-bills'
    | '/personal-details'
    | '/send'
    | '/signup'
    | '/transaction-history'
    | '/transfer'
    | '/varo-card'
    | '/account/$id'
  id:
    | '__root__'
    | '/'
    | '/account-numbers'
    | '/add-cash'
    | '/cashback'
    | '/fund-instantly'
    | '/install'
    | '/linked-accounts'
    | '/login'
    | '/manage-cards'
    | '/move-money'
    | '/my-varo'
    | '/pay-bills'
    | '/personal-details'
    | '/send'
    | '/signup'
    | '/transaction-history'
    | '/transfer'
    | '/varo-card'
    | '/account/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountNumbersRoute: typeof AccountNumbersRoute
  AddCashRoute: typeof AddCashRoute
  CashbackRoute: typeof CashbackRoute
  FundInstantlyRoute: typeof FundInstantlyRoute
  InstallRoute: typeof InstallRoute
  LinkedAccountsRoute: typeof LinkedAccountsRoute
  LoginRoute: typeof LoginRoute
  ManageCardsRoute: typeof ManageCardsRoute
  MoveMoneyRoute: typeof MoveMoneyRoute
  MyVaroRoute: typeof MyVaroRoute
  PayBillsRoute: typeof PayBillsRoute
  PersonalDetailsRoute: typeof PersonalDetailsRoute
  SendRoute: typeof SendRoute
  SignupRoute: typeof SignupRoute
  TransactionHistoryRoute: typeof TransactionHistoryRoute
  TransferRoute: typeof TransferRoute
  VaroCardRoute: typeof VaroCardRoute
  AccountIdRoute: typeof AccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-numbers': {
      id: '/account-numbers'
      path: '/account-numbers'
      fullPath: '/account-numbers'
      preLoaderRoute: typeof AccountNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-cash': {
      id: '/add-cash'
      path: '/add-cash'
      fullPath: '/add-cash'
      preLoaderRoute: typeof AddCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashback': {
      id: '/cashback'
      path: '/cashback'
      fullPath: '/cashback'
      preLoaderRoute: typeof CashbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-instantly': {
      id: '/fund-instantly'
      path: '/fund-instantly'
      fullPath: '/fund-instantly'
      preLoaderRoute: typeof FundInstantlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-accounts': {
      id: '/linked-accounts'
      path: '/linked-accounts'
      fullPath: '/linked-accounts'
      preLoaderRoute: typeof LinkedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-cards': {
      id: '/manage-cards'
      path: '/manage-cards'
      fullPath: '/manage-cards'
      preLoaderRoute: typeof ManageCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-money': {
      id: '/move-money'
      path: '/move-money'
      fullPath: '/move-money'
      preLoaderRoute: typeof MoveMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-varo': {
      id: '/my-varo'
      path: '/my-varo'
      fullPath: '/my-varo'
      preLoaderRoute: typeof MyVaroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bills': {
      id: '/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof PayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-details': {
      id: '/personal-details'
      path: '/personal-details'
      fullPath: '/personal-details'
      preLoaderRoute: typeof PersonalDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction-history': {
      id: '/transaction-history'
      path: '/transaction-history'
      fullPath: '/transaction-history'
      preLoaderRoute: typeof TransactionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varo-card': {
      id: '/varo-card'
      path: '/varo-card'
      fullPath: '/varo-card'
      preLoaderRoute: typeof VaroCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$id': {
      id: '/account/$id'
      path: '/account/$id'
      fullPath: '/account/$id'
      preLoaderRoute: typeof AccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountNumbersRoute: AccountNumbersRoute,
  AddCashRoute: AddCashRoute,
  CashbackRoute: CashbackRoute,
  FundInstantlyRoute: FundInstantlyRoute,
  InstallRoute: InstallRoute,
  LinkedAccountsRoute: LinkedAccountsRoute,
  LoginRoute: LoginRoute,
  ManageCardsRoute: ManageCardsRoute,
  MoveMoneyRoute: MoveMoneyRoute,
  MyVaroRoute: MyVaroRoute,
  PayBillsRoute: PayBillsRoute,
  PersonalDetailsRoute: PersonalDetailsRoute,
  SendRoute: SendRoute,
  SignupRoute: SignupRoute,
  TransactionHistoryRoute: TransactionHistoryRoute,
  TransferRoute: TransferRoute,
  VaroCardRoute: VaroCardRoute,
  AccountIdRoute: AccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
